import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/Header";
import { LanguageProvider } from "./components/LanguageContext";
import { Footer } from "./components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col relative">
        <LanguageProvider>
          <Header />
          <main className="max-w-7xl mx-auto w-full">
            {children}
          </main>
        </LanguageProvider>
      </body>
    </html>
  );
}
