name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: |
         git pull
         npm install 
         npm run build
         pm2 restart sapore-website
         pm2 save
      
    #   - name: Set up SSH
    #     uses: webfactory/ssh-agent@v0.5.1
    #     with:
    #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       host: 192.168.1.180 # Your server's IP address
    #       username: k20 # Your server's username
    #       run: |
    #         cd /var/www/sapore-website
    #         git pull
    #         npm install
    #         npm run build
    #         pm2 restart sapore-website
    #         pm2 save